services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-lesson
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-lesson
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-lesson:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-lesson:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on: 
      - kafka
    ports:
      - "9001:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kui
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-lesson:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-lesson:2181
